style(dbgdiv, { userSelect: "none" })
css(".button", { display: "inline", margin: 5, padding: 10, borderRadius: 10 })
css(".button", { background: "white", cursor: "pointer" })
dom({ child: "⏮", onclick: () => refresh(), class: "button" }, dbgdiv)
dom({ child: "⏪", onclick: () => toback(), class: "button" }, dbgdiv)
dom({ child: "🔁", onclick: () => tocurr(), class: "button" }, dbgdiv)
dom({ child: "⏩", onclick: () => step(), class: "button" }, dbgdiv)
dom({ child: "⏬", onclick: () => runtill(Infinity), class: "button" }, dbgdiv)
dom({ child: "⏭", onclick: () => toend(), class: "button" }, dbgdiv)