defineup("env")
definedown("a")
definedown("b")
definedown("c")
definedown("d")
definedown("e")
definedown("f")
definedown("g")
definedown("h")
definedown("i")
definedown("j")

$.process = () => {
  if (!$.env) { $.env = oneenv.newenv() }
  const $$ = env.$$; $$.list.push([])
  $.a = Object.create(env)
  $.a.$$ = structuredClone($$)
  $.b = Object.create(env)
  $.b.$$ = structuredClone($$)
  $.c = Object.create(env)
  $.c.$$ = structuredClone($$)
  $.d = Object.create(env)
  $.d.$$ = structuredClone($$)
  $.e = Object.create(env)
  $.e.$$ = structuredClone($$)
  $.f = Object.create(env)
  $.f.$$ = structuredClone($$)
  $.g = Object.create(env)
  $.g.$$ = structuredClone($$)
  $.h = Object.create(env)
  $.h.$$ = structuredClone($$)
  $.i = Object.create(env)
  $.i.$$ = structuredClone($$)
  $.j = Object.create(env)
  $.j.$$ = structuredClone($$)
}